# Notable references
# - http://www.projectatomic.io/blog/2014/09/running-syslog-within-a-docker-container/

FROM python:3
LABEL application="behave_test"
RUN pip install behave && \
    pip install requests && \
    pip install pyhamcrest && \
    pip install jmespath && \
    pip install rfc5424-logging-handler && \
    pip install kafka-python

VOLUME /tmp/test
WORKDIR /tmp/test
CMD ["behave", "--junit", "--junit-directory", "/tmp/test/behave/reports", "behave/features"]
