FROM registry.access.redhat.com/ubi7/ubi-minimal
ENV container=docker
COPY repo/rhel/RPM-GPG-KEY-Adiscon /etc/pki/rpm-gpg/RPM-GPG-KEY-Adiscon
COPY repo/rhel/rsyslog-redhat7-ubi.repo /etc/yum.repos.d/rsyslog.repo
ARG RSYSLOG_VERSION='8.2212.0'
RUN microdnf --setopt=tsflags=nodocs -y install \
  rsyslog-${RSYSLOG_VERSION} \
  rsyslog-kafka-${RSYSLOG_VERSION}
RUN rm -rf /etc/rsyslog.d/ \
  && rm -f /etc/rsyslog.conf
COPY rsyslog.conf /etc/rsyslog.conf
EXPOSE 514/udp
#ENV RSYSLOG_DEBUG='Debug LogFuncFlow FileTrace=imkafka.c'
CMD bash -c 'rsyslogd -n'
